### ISSUE TITLE
How to change scale of colors?

### ISSUE THREAD

**Issue by paynito** [prabhasp/NepalMaps#1]
Hi. It seems that the 0=white to 100=dark blue is baked-in and comes from the highest and lowest 
values in the .csv file.  How could one change this to make more of their values seem to be blue or white? How can you shift the scale as it were if you want to emphasize something like below $2/day poverty line?  I would love to see you release this as a more up-to-date R package with proper documentation. But I see that you have moved more toward the plastic arts recently.  Anyway, great work! I found your codebase easier to use than 2 or 3 other choropleth packages.

**Comment by prabhasp** [comment]
This is the line in NepalMapUtils.R that does the "baking in".
> scale_fill_gradient(low="white", high=muted("blue"))

If you modify the function to make those colors optional arguments and make
a pull request, I'm happy to review.

**Comment by paynito** [comment]
Yes, I'll have to look at some other code to see if it can be adapted. Some way to push the mid-value (half-white/half-blue) to where you want it, maybe down to 20%, maybe up to 90%, to skew the readings.

**Comment by prabhasp** [comment]
A good place to start are the scale_fill_X functions in ggplot2
documentation.

**Comment by paynito** [comment]
Thank you, your code was very easy to plug my shape file into and get up and running.
